version: "3"
services:
  web:
    image: wiki
    restart: always
    ports:
      - 8080:80
    links:
      - parsoid
    volumes:
      - ./devmounts/images:/data/images
      - ./devmounts/sec:/sec
      - ./devmounts/conf:/conf
  parsoid:
    image: thenets/parsoid:0.10
    restart: always
    environment:
      PARSOID_DOMAIN_web: http://web/api.php
