---
name: Build and push Docker image
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wiki-dave-io:latest
    - name: Tag the Docker image with the short commit hash
      run: docker tag wiki-dave-io:latest docker.pkg.github.com/daveio/packages/wiki-dave-io:$(echo -n ${GITHUB_SHA} | cut -b -7)
    - name: Tag the Docker image with latest
      run: docker tag wiki-dave-io:latest docker.pkg.github.com/daveio/packages/wiki-dave-io:latest
    - name: Log in to GHPR
      run: echo ${GHPR_TOKEN} | docker login docker.pkg.github.com --username daveio --password-stdin
      env:
        GHPR_TOKEN: ${{ secrets.ghprToken }}
    - name: Push to GHPR (short commit hash)
      run: docker push docker.pkg.github.com/daveio/packages/wiki-dave-io:$(echo -n ${GITHUB_SHA} | cut -b -7)
    - name: Push to GHPR (latest)
      run: docker push docker.pkg.github.com/daveio/packages/wiki-dave-io:latest
